# Generated by Django 3.0 on 2020-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activité',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
