# Generated by Django 3.0 on 2020-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activité_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activité',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs'),
        ),
    ]
